packages:
  - 'packages/*'
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
overrides:
  vite: 'catalog:'
allowBuilds:
  esbuild: false
  simple-git-hooks: false
shamefullyHoist: true
ignoreWorkspaceRootCheck: true
minimumReleaseAgeExclude:
  - '@soybeanjs/fetch@0.1.0'
  - '@soybeanjs/cli@1.8.3'
