packages:
  - 'packages/*'
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.6
  vite-plus: 0.2.6
overrides:
  vite: 'catalog:'
allowBuilds:
  esbuild: false
  simple-git-hooks: false
shamefullyHoist: true
ignoreWorkspaceRootCheck: true
minimumReleaseAgeExclude:
  - '@soybeanjs/fetch@0.1.0'
